### ISSUE TITLE
discord api policy

### ISSUE THREAD

**Issue by MhmCats** [FuckingToasters/discordmembers#1]
this repository is directly breaking the discord developer policy which states that
> You may not use the APIs in any way to: scrape any Discord Data;

or 
> disclose any user’s Discord Data without their specific, informed consent;

this is not for "educational" purposes as i can see no clear purposes where this would be used for education. please delete this repository immediately.

**Comment by FuckingToasters** [comment]
> this repository is directly breaking the discord developer policy which states that
> 
> > You may not use the APIs in any way to: scrape any Discord Data;
> 
> or
> 
> > disclose any user’s Discord Data without their specific, informed consent;
> 
> this is not for "educational" purposes as i can see no clear purposes where this would be used for education. please delete this repository immediately.

I am sorry to hear that. I thought, it is educational so others see how easy such stuff is and maybe could change their name regullary if they notice something like that. i understand that it might be against the ToS and because i dont want to do such thing, i delete this repo asap. just let you know
